// <auto-generated />
using System;
using BethanysPieShop.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BethanysPieShop.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210104100218_ShoppingCartAdded")]
    partial class ShoppingCartAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("BethanysPieShop.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Fruit pies"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Cheese cakes"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Seasonal pies"
                        });
                });

            modelBuilder.Entity("BethanysPieShop.Models.Pie", b =>
                {
                    b.Property<int>("PieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ImageThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("InStock")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPieOfTheWeek")
                        .HasColumnType("bit");

                    b.Property<string>("LongDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PieId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Pies");

                    b.HasData(
                        new
                        {
                            PieId = 1,
                            CategoryId = 1,
                            ImageThumbnailUrl = "https://tse2.mm.bing.net/th?id=OIP.Qz8R5MTv4KKTT-OVw8y_fgHaHa&pid=Api&P=0&w=300&h=300",
                            ImageUrl = "https://tse2.mm.bing.net/th?id=OIP.Qz8R5MTv4KKTT-OVw8y_fgHaHa&pid=Api&P=0&w=300&h=300",
                            InStock = true,
                            IsPieOfTheWeek = true,
                            LongDescription = "Our classic apple pie takes a shortcut with easy Pillsbury™ refrigerated pie crust! Baked with a filling of fresh apples and warm spices, there is as much simple joy in preparing this pie as there is in eating it",
                            Name = "Apple pie",
                            Price = 12.95m,
                            ShortDescription = "Perfect Apple Pie."
                        },
                        new
                        {
                            PieId = 2,
                            CategoryId = 2,
                            ImageThumbnailUrl = "https://tse4.mm.bing.net/th?id=OIP.Y63KW4HDy401PiQtVH-qtAHaE8&pid=Api&P=0&w=229&h=153",
                            ImageUrl = "https://tse4.mm.bing.net/th?id=OIP.Y63KW4HDy401PiQtVH-qtAHaE8&pid=Api&P=0&w=229&h=153",
                            InStock = true,
                            IsPieOfTheWeek = true,
                            LongDescription = "Cool and then remove cake from pan by loosening edges with a knife. Place frozen blueberries on top of cake. Melt jelly and spoon over blueberries to glaze. Chill until ready to serve.",
                            Name = "Blueberry Cake",
                            Price = 18.95m,
                            ShortDescription = "You'll love it."
                        },
                        new
                        {
                            PieId = 3,
                            CategoryId = 3,
                            ImageThumbnailUrl = "https://tse1.mm.bing.net/th?id=OIP.XmO7CJJxtwMD-3osPGe45gD6D6&pid=Api&P=0&w=300&h=300",
                            ImageUrl = "https://tse1.mm.bing.net/th?id=OIP.XmO7CJJxtwMD-3osPGe45gD6D6&pid=Api&P=0&w=300&h=300",
                            InStock = true,
                            IsPieOfTheWeek = true,
                            LongDescription = "My guests always expect me to create something new, a real showstopper! Here is my latest creation. Decorate with whipped cream just before serving. ",
                            Name = "Cheese Cake",
                            Price = 18.95m,
                            ShortDescription = "Plain cheese cake. Plain pleasure."
                        });
                });

            modelBuilder.Entity("BethanysPieShop.Models.ShoppingCartItem", b =>
                {
                    b.Property<int>("ShoppingCartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int?>("PieId")
                        .HasColumnType("int");

                    b.Property<string>("ShoppingCartId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ShoppingCartItemId");

                    b.HasIndex("PieId");

                    b.ToTable("ShoppingCartItems");
                });

            modelBuilder.Entity("BethanysPieShop.Models.Pie", b =>
                {
                    b.HasOne("BethanysPieShop.Models.Category", "Category")
                        .WithMany("Pies")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BethanysPieShop.Models.ShoppingCartItem", b =>
                {
                    b.HasOne("BethanysPieShop.Models.Pie", "Pie")
                        .WithMany()
                        .HasForeignKey("PieId");

                    b.Navigation("Pie");
                });

            modelBuilder.Entity("BethanysPieShop.Models.Category", b =>
                {
                    b.Navigation("Pies");
                });
#pragma warning restore 612, 618
        }
    }
}
